export const AFFIRMATIONS = [
  "Believe you can and you're halfway there.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "The only way to do great work is to love what you do.",
  "Don't watch the clock; do what it does. Keep going.",
  "Everything you've ever wanted is on the other side of fear.",
  "Hardships often prepare ordinary people for an extraordinary destiny.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "You are never too old to set another goal or to dream a new dream.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Act as if what you do makes a difference. It does.",
  "Success is stumbling from failure to failure with no loss of enthusiasm.",
  "Keep your face always toward the sunshine—and shadows will fall behind you.",
  "It always seems impossible until it's done.",
  "Your time is limited, so don't waste it living someone else's life.",
  "The best way to predict the future is to create it.",
  "Do what you can, with what you have, where you are.",
  "Be the change that you wish to see in the world.",
  "In the middle of every difficulty lies opportunity.",
  "Start where you are. Use what you have. Do what you can.",
  "Don't let yesterday take up too much of today.",
  "Every moment is a fresh beginning.",
  "Dream big and dare to fail.",
  "Turn your wounds into wisdom.",
  "The secret of getting ahead is getting started.",
  "It's not whether you get knocked down, it's whether you get up.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "If you can dream it, you can do it.",
  "Limit your 'always' and your 'nevers'.",
  "Quality is not an act, it is a habit.",
  "There are no shortcuts to any place worth going.",
  "You must be the change you wish to see in the world.",
  "The way to get started is to quit talking and begin doing.",
  "Action is the foundational key to all success.",
  "Don't be afraid to give up the good to go for the great.",
  "I find that the harder I work, the more luck I seem to have.",
  "Success is not the key to happiness. Happiness is the key to success.",
  "The successful warrior is the average man, with laser-like focus.",
  "Successful people do what unsuccessful people are not willing to do.",
  "Don't wish it were easier. Wish you were better.",
  "The only person you are destined to become is the person you decide to be.",
  "A year from now you may wish you had started today.",
  "Whatever you are, be a good one.",
  "The best revenge is massive success.",
  "Motivation is what gets you started. Habit is what keeps you going.",
  "The only place where success comes before work is in the dictionary.",
  "Opportunities don't happen. You create them.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "You miss 100% of the shots you don't take.",
  "I have not failed. I've just found 10,000 ways that won't work.",
  "Winning isn't everything, but wanting to win is.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Your life does not get better by chance, it gets better by change.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "The secret to success is to know something nobody else knows.",
  "Do not wait to strike till the iron is hot; but make it hot by striking.",
  "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.",
  "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.",
  "The road to success and the road to failure are almost exactly the same.",
  "The ladder of success is best climbed by stepping on the rungs of opportunity.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Everything comes to him who hustles while he waits.",
  "Success is liking yourself, liking what you do, and liking how you do it.",
  "If you really look closely, most overnight successes took a long time.",
  "Small deeds done are better than great deeds planned.",
  "Knowledge is power. Information is liberating. Education is the premise of progress.",
  "An investment in knowledge pays the best interest.",
  "Education is the most powerful weapon which you can use to change the world.",
  "The more that you read, the more things you will know. The more that you learn, the more places you'll go.",
  "Learning never exhausts the mind.",
  "The beautiful thing about learning is that no one can take it away from you.",
  "Live as if you were to die tomorrow. Learn as if you were to live forever.",
  "Change is the end result of all true learning.",
  "Education is the kindling of a flame, not the filling of a vessel.",
  "The expert in anything was once a beginner.",
  "It is not that I'm so smart. But I stay with the questions much longer.",
  "Study while others are sleeping; work while others are loafing; prepare while others are playing; and dream while others are complaining.",
  "The more you learn, the more you earn.",
  "The only thing that interferes with my learning is my education.",
  "Wisdom is not a product of schooling but of the lifelong attempt to acquire it.",
  "He who opens a school door, closes a prison.",
  "Develop a passion for learning. If you do, you will never cease to grow.",
  "The mind is not a vessel to be filled but a fire to be ignited.",
  "Learn from yesterday, live for today, hope for tomorrow.",
  "The direction in which education starts a man will determine his future in life.",
  "Tell me and I forget, teach me and I may remember, involve me and I learn.",
  "Instruction ends in the schoolroom, but education ends only with life.",
  "The roots of education are bitter, but the fruit is sweet.",
  "A well-educated mind will always have more questions than answers.",
  "The objective of education is to prepare the young to educate themselves throughout their lives.",
  "You don't have to be great to start, but you have to start to be great.",
  "The way to learn is to do.",
  "Education is not the filling of a pail, but the lighting of a fire.",
  "Formal education will make you a living; self-education will make you a fortune.",
  "The purpose of education is to replace an empty mind with an open one.",
  "He who learns but does not think, is lost! He who thinks but does not learn is in great danger.",
  "To learn a language is to have one more window from which to look at the world.",
  "Whatever the cost of our libraries, the price is cheap compared to that of an ignorant nation.",
  "Always walk through life as if you have something new to learn and you will.",
  "Courage is not the absence of fear, but rather the assessment that something else is more important than fear.",
  "The best way out is always through.",
  "Keep going. Everything you need will come to you at the perfect time.",
  "Your only limit is your mind.",
  "Don't stop when you're tired. Stop when you're done.",
  "Focus on your goal. Don't look in any direction but ahead.",
  "Be stronger than your strongest excuse.",
  "A little progress each day adds up to big results.",
  "Discipline is doing what needs to be done, even if you don't want to do it.",
  "Consistency is what transforms average into excellence.",
  "Push yourself, because no one else is going to do it for you.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Don't tell people your dreams. Show them.",
  "Great things never come from comfort zones.",
  "Dream it. Wish it. Do it.",
  "Stay focused and never give up.",
  "Wake up with determination. Go to bed with satisfaction.",
  "The struggle you're in today is developing the strength you need for tomorrow.",
  "Don't quit. Suffer now and live the rest of your life as a champion.",
  "It's going to be hard, but hard does not mean impossible.",
  "Your focus determines your reality.",
  "Hard work beats talent when talent doesn't work hard.",
  "Do something today that your future self will thank you for.",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  "Success doesn't just find you. You have to go out and get it.",
  "Don't wait for opportunity. Create it.",
  "Sometimes later becomes never. Do it now.",
  "Great things take time.",
  "Be so good they can't ignore you.",
  "Stay positive, work hard, make it happen.",
  "Difficult roads often lead to beautiful destinations.",
  "The only way to do great work is to love what you do.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "Do what you can, with what you have, where you are.",
  "Believe in yourself and all that you are.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "Every journey begins with a single step.",
  "Don't let the noise of others' opinions drown out your own inner voice.",
  "If you want to live a happy life, tie it to a goal, not to people or things.",
  "Never give up on a dream just because of the time it will take to accomplish it.",
  "You are enough just as you are.",
  "Be kind to yourself.",
  "You've got this.",
  "One day or day one. You decide.",
  "Everything you need is already within you.",
  "Small steps in the right direction can turn out to be the biggest steps of your life.",
  "If it doesn't challenge you, it won't change you.",
  "You don't find willpower, you create it.",
  "Doubt kills more dreams than failure ever will.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Don't count the days, make the days count.",
  "Be patient with yourself. Self-growth is tender; it's holy ground.",
  "Your potential is endless.",
  "Do what you love and you'll never work a day in your life.",
  "Action is the foundational key to all success.",
  "What you do today can improve all your tomorrows.",
  "Progress, not perfection.",
  "It's never too late to be what you might have been.",
  "Life is 10% what happens to us and 90% how we react to it.",
  "Your energy introduces you before you even speak.",
  "Choose a job you love, and you will never have to work a day in your life.",
  "Work hard in silence, let your success be your noise.",
  "Don't be afraid to fail, be afraid not to try.",
  "The only way to reach the top is to start from the bottom.",
  "Don't be pushed by your problems. Be led by your dreams.",
  "Failure is the opportunity to begin again more intelligently.",
  "Obstacles are those frightful things you see when you take your eyes off your goal.",
  "Your time is limited, so don't waste it living someone else's life.",
  "You are the master of your fate, you are the captain of your soul.",
  "In the end, we only regret the chances we didn't take.",
  "You're only one workout away from a good mood.",
  "Don't let what you cannot do interfere with what you can do.",
  "Life is short, and it's up to you to make it sweet.",
  "The secret to getting ahead is getting started.",
  "Be fearless in the pursuit of what sets your soul on fire.",
  "Your passion is waiting for your courage to catch up.",
  "Strength does not come from physical capacity. It comes from an indomitable will.",
  "If you want something you've never had, you must be willing to do something you've never done.",
  "Start where you are. Use what you have. Do what you can.",
  "Be so busy improving yourself that you have no time to criticize others.",
  "Life is about making an impact, not making an income.",
  "The mind is everything. What you think you become.",
  "Everything you've ever wanted is on the other side of fear.",
  "It doesn't matter how slowly you go as long as you do not stop.",
  "Don't judge each day by the harvest you reap but by the seeds that you plant.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "A person who never made a mistake never tried anything new.",
  "If you're going through hell, keep going.",
  "The best way to predict the future is to create it.",
  "I would rather die of passion than of boredom.",
  "Eighty percent of success is showing up.",
  "Success is not in what you have, but who you are.",
  "Your life is your message to the world. Make sure it's inspiring.",
  "Don't wait. The time will never be just right.",
  "If you want to achieve greatness stop asking for permission.",
  "Things work out best for those who make the best of how things work out.",
  "To live a creative life, we must lose our fear of being wrong.",
  "If you are not willing to risk the usual you will have to settle for the ordinary.",
  "Trust because you are willing to accept the risk, not because it's safe or certain.",
  "All our dreams can come true if we have the courage to pursue them.",
  "Good things come to people who wait, but better things come to those who go out and get them.",
  "Success is the sum of small efforts, repeated day-in and day-out.",
  "I find that the harder I work, the more luck I seem to have.",
  "The starting point of all achievement is desire.",
  "Success is not the key to happiness. Happiness is the key to success.",
  "The road to success and the road to failure are almost exactly the same.",
  "The function of leadership is to produce more leaders, not more followers.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "The only person you are destined to become is the person you decide to be.",
  "Don't let what you cannot do interfere with what you can do.",
  "Successful people do what unsuccessful people are not willing to do.",
  "A journey of a thousand miles begins with a single step.",
  "Don't count the days, make the days count.",
  "Life is what happens when you're busy making other plans."
];
