// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpxmitaveezpinajrutw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJweG1pdGF2ZWV6cGluYWpydXR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY5MzkxMDYsImV4cCI6MjA4MjUxNTEwNn0.VgEfuMQotGVHnCYyXKkRHKzOcuSzRShH1edd8rl2vlk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});